version: "3"
services:
  comp_env:
    build:
      context: .
      dockerfile: Dockerfile
    user: 1000:1000
    volumes:
      - $PWD/atcoder:/home/ubuntu/contest
    working_dir: /home/ubuntu/contest
    tty: true
